version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/application
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 900
      runas: root